### ISSUE TITLE
Bug: Unable to run isotope cli on OSX

### ISSUE THREAD

**Issue by techmaniack** [isotope-rs/isotope#6]
**Issue**: isotope cli throws an exception.
```
> brew install isotope-rs/homebrew-isotope/isotope
==> Tapping isotope-rs/isotope
...
🍺  /usr/local/Cellar/isotope/0.0.8: 5 files, 7.3MB, built in 24 seconds

> RUST_BACKTRACE=full RUST_BACKTRACE=1 isotope analyze -a s3

██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 1/0thread 'tokio-runtime-worker' panicked at src/utils/mod.rs:9:45:
called `Result::unwrap()` on an `Err` value: NotPresent
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src/analyze/mod.rs:121:39:
called `Result::unwrap()` on an `Err` value: RecvError
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The aws cli is configured properly.
```
> aws s3 ls
2020-05-07 15:50:27 aws-cloudtrail-logs-XXXXXXXX-XXXXXXXX
```

The environment variables are configured as per README
```
> env | grep BEDROCK
BEDROCK_REGION=eu-central-1
BEDROCK_MODEL=anthropic.claude-v2
```

More details about my local environment:
```
> aws --version
aws-cli/2.13.26 Python/3.11.6 Darwin/22.5.0 source/x86_64 prompt/off

> uname -a
Darwin memons-MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

> arch
i386

> sw_vers
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
```

**Comment by AlexsJones** [comment]
Thanks for this, can you please test whether you get the same results when using an individual analyzer?
```
isotope analyze -a s3
```

Let me know what that yields please

**Comment by techmaniack** [comment]
Yes, the same error with an individual analyzer.

**Comment by techmaniack** [comment]
I was going through the code and found the issue, it was failing because `AWS_REGION` env variable was not set and the code expects it. If not set, could it default to `us-east-1`? or maybe loop over all regions?

https://github.com/isotope-rs/isotope/blob/635539a230cd4df2e97c9596d187b9f835891526/src/utils/mod.rs#L9

I feel this should be added to the README. It's a fairly small change, let me know if you would be ok with a PR for this :)

Btw, there is another issue now. When I ran the sg analyzer, there was no advice even though it says security group is insecure.

```
> AWS_REGION=us-east-1 RUST_BACKTRACE=full RUST_BACKTRACE=1 isotope analyze -e -a sg -j

████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 1/0Running Security Groups analyzer
{
  "sg": [
    {
      "message": "Insecure security group: sg-xxxxxxxxxxxx",
      "analyzer_name": "sg",
      "advice": ""
    }
  ]
}
```

**Comment by etolbakov** [comment]
I also stumbled upon the same issue with the mission region when was playing with the tool!

**Comment by AlexsJones** [comment]
Thanks both, I appreciate your helpfulness - This is in the readme, but I think we need to make an explicit check in code
```
export AWS_REGION="" ( e.g. eu-west-2 //wherever your VPC is )
```
